# Generated by Django 3.0.6 on 2020-05-07 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Full name')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Image')),
                ('total_account', models.IntegerField(default=0, verbose_name='Total account')),
                ('auth_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Code for sign in')),
                ('currency', models.CharField(blank=True, choices=[('KGS', 'KGS'), ('RUB', 'RUB'), ('USD', 'USD')], default='som', max_length=3, verbose_name='Choice currency')),
                ('phone_number', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneyapp.Person', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_value', models.PositiveIntegerField(default=0, verbose_name='Income value')),
                ('expense_value', models.PositiveIntegerField(default=0, verbose_name='Expense value')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneyapp.Category', verbose_name='category')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneyapp.Person', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-id'],
            },
        ),
    ]
