# Generated by Django 3.0.6 on 2020-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0002_remove_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='currency',
            field=models.CharField(blank=True, choices=[('income', 'income'), ('expense', 'expense')], default='som', max_length=7, verbose_name='Budget Choice'),
        ),
    ]
