# Generated by Django 3.0.6 on 2020-05-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0003_category_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='currency',
            new_name='budget_choice',
        ),
    ]
